### ISSUE TITLE
dashboard section 1 enhancing

### ISSUE THREAD

**Issue by LucaNyckees** [LucaNyckees/recommendation_system#27]
### Problem

Make data viz section of dashboard better.

### ToDo

- [ ] add time charts for total price and total number of ratings
- [ ] add per-month total price and per-month total number of ratings as barplot
- [ ] review whole dashboard flow
