### ISSUE TITLE
guidelines and ideas for the bert reviews regressor

### ISSUE THREAD

**Issue by LucaNyckees** [LucaNyckees/recommendation_system#3]
### Problem

We wish to take notes of a few ideas as this project starts.

### ToDo

- [ ] Reduce the size of the inputs by subsampling the data, maybe after performing some kind of PCA : choose a set of inputs with maximum variance. Large inputs are computationally expensive and not always useful.
- [ ] Implement a visual summary of the model performance
- [x] Try to understand and eliminate warnings when training the model
- [ ] check out [this link](https://www.datacamp.com/blog/llm-interview-questions?dc_referrer=https%3A%2F%2Fwww.google.com%2F), go the "importance of model interpretability" question and try playing with those techniques
