### ISSUE TITLE
refactoring of nlp folder

### ISSUE THREAD

**Issue by LucaNyckees** [LucaNyckees/recommendation_system#32]
### Problem

NLP folder structure becomes poorly thought.

### ToDo

- [ ] add the BERT classifier in the nlp/sentiment_analysis/classifiers.py file and integrate it correctly
- [ ] add the BERT regressor in a new file nlp/sentiment_analysis/regressors.py and integrate it correctly
- [ ] think of what to do with the embedder.py file (maybe leave it as it is)
