### ISSUE TITLE
recommender demo

### ISSUE THREAD

**Issue by LucaNyckees** [LucaNyckees/recommendation_system#35]
### Problem

The Dash app still needs a recommender demo section.

### ToDo

- [ ] implement demo

Ideas for the frontend
- [ ] each time you log, you select 3 categories you are interested in, amongst a list of proposed Amazon product categories
- [ ] then you fill in basic demographic information (e.g. age, city)
- [ ] then the recommender system shall assign you similar users and suggest you their favorite items from the 3 categories

In the backend, I will have to
- [x] create and fill a new table called "rs_users" with fake/generated demographic information
- [ ] integrate the recommender system with routes to the dashboard
