### ISSUE TITLE
knn/dbscan/cosimilarity based user clusters

### ISSUE THREAD

**Issue by LucaNyckees** [LucaNyckees/recommendation_system#5]
### Problem

We want to add a brick to the recommender system, which takes into account similarities between users.

### ToDo

- [ ] create a matrix with a row for each user, and then for each column (=product), the interaction the user had with that product (no interaction, or purchase with some rating)
- [ ] with this matrix, each user is a vector of dimension (1, total_nb_of_products). Cluster those vectors with any algorithm passed as argument (can be kNN, DBSCAN, cosine similarity etc., as long as it does not suffer too much from high dimensionality)
- [ ] integrate this brick to the recommendation system by proposing products of similar users for the active user
