### ISSUE TITLE
more solid sentiment analysis component

### ISSUE THREAD

**Issue by LucaNyckees** [LucaNyckees/recommendation_system#9]
### Problem

We have to consider a few topics to make our sentiment analysis component more robust and complete.

### ToDo

- [ ] address class imbalance in sentiment labels for training our sentiment classifier(s)
- [x] see how a random forest classifier does compared to our xgboost model
- [ ] integrate component into framework
